default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: owhat3

test:
  <<: *default
  database: owhat3

production:
  <<: *default
  database: owhat3

owhat2:
  adapter: mysql2
  encoding: utf8
  username: owhat
  password: 0gsRKXuSksdb
  host: rdsqmm3aqjafri3.mysql.rds.aliyuncs.com
  pool: 50
  database: owhat
