# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ebcbb078df1150baf80d85641f9376aa0efa81b9f99bec5e1472c97422c2d5e1c0512ec8df38b98de4fb4700d521e0dc9ab42dfad76cf2c7ff7996894767b1
  redis_host: 127.0.0.1
  sms_user: test
  sms_password: test
  qiniu_access_key: nlOeZ_xrmy4NIjcqehaE6J9fxiG768a44V0_YnQz
  qiniu_secret_key: b1VXQyGcGUbVXxW5rVprpRQ_CNkTGb1E6s55t_k1
  qiniu_host: 7xlmj0.com1.z0.glb.clouddn.com
  qiniu_host_name: staging
  alipay_pid: 2088511639557826
  alipay_key: rbzx7vao1ubcp6e8uq0p193t6u5bjbbc
  alipay_seller_email: ostarmkt@sina.com
  elasticsearch_host: http://localhost:9200 #http://123.56.236.52:9205/
  weixin:
    payment:
      appid: wx9e3074c883612e78
      mch_id: 1317590401
      key: OIBfmJoW4CDUwRmAqiytqYxp3ulxfz8a

  weixin_app:
    payment:
      appid: wx464f26f5c384981f
      mch_id: 1285394801
      key: 67a64fd33257415e4ea020d71153c06f
      wx_key: OIBfmJoW4CDUwRmAqiytqYxp3ulxfz8a

  rongcloud:
    app_key: vnroth0kr5qvo
    app_secret: yaeGzZKi6Vovy

test:
  secret_key_base: 1cd717742d6d8d6bbec770accf1a2de7decadc4781c56faae7a4e6ded916d7e7b39f3eb44bca643917a7e6bef4a5d0c3ce2bf2909f00c6892cd815836a27cc57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 91ebcbb078df1150baf80d85641f9376aa0efa81b9f99bec5e1472c97422c2d5e1c0512ec8df38b98de4fb4700d521e0dc9ab42dfad76cf2c7ff7996894767b1
  qiniu_access_key: nlOeZ_xrmy4NIjcqehaE6J9fxiG768a44V0_YnQz
  qiniu_secret_key: b1VXQyGcGUbVXxW5rVprpRQ_CNkTGb1E6s55t_k1
  qiniu_host: http://7xlmj0.com1.z0.glb.clouddn.com
  qiniu_host_name: staging
